### ISSUE TITLE
Expose expanded property

### ISSUE THREAD

**Issue by Wheater** [glutengo/angular-mgl-timeline#13]
I would like to change styles based on the expanded status.

**Comment by glutengo** [comment]
Sounds reasonable. 
@Wheater In what way would you like it to be exposed? I could either emit an event to the timeline-entry component or add a class to the element if it is expanded.

**Comment by glutengo** [comment]
Okay, I'll come up with something in the next days!

Thanks, that's great to hear, it's my first and only one out there so far

**Comment by nikhil4326** [comment]
Thanks @glutengo for adding new input parameter. I don't want content to highlight or any changes to circle(step) happen on click event. do you have workaround on this? Just simply wants to stop behaviour of clicking on timeline.

**Comment by glutengo** [comment]
@nikhil4326 This should have been a new issue, it's unrelated to the initial question. However your desired behavior is possible. I've updated the stackblitz demo:
https://stackblitz.com/edit/angular-mgl-timeline
If you have further questions regarding this, please add a new issue.

**Comment by glutengo** [comment]
Version 0.2.1 was just released. The only change is the inclusion of this feature request. Have fun!
