### ISSUE TITLE
Expose side property

### ISSUE THREAD

**Issue by raphaelman** [glutengo/angular-mgl-timeline#14]
In a design prospective, I think the side property would be helpful.
I am trying to set style depending on the side where the box is.

**Comment by glutengo** [comment]
Hm I'm not sure if I understood you correctly. Do you want to style entries which are displayed on the right different to those which are displayed on the left?

If that's the case, this can easily be achieved by providing a class depending on the index, like this:
`<mgl-timeline [toggle]="true">
   <mgl-timeline-entry *ngFor="let entry of entries; let i = index" [class.left]="i % 2 === 0" [class.right]="i % 2 !== 0">...</mgl-timeline-entry>
</mgl-timeline>`

If you want to achieve something else, please provide a more specific description of your issue.

**Comment by raphaelman** [comment]
You're right.
I get what meant with that simple line:
`[ngClass]="i % 2 === 0 ? 'left' :'right'"`
