### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by JP-Basson** [glutengo/angular-mgl-timeline#15]
Hi, is there anyway to disable the animations when clicking on events?

**Comment by glutengo** [comment]
It is now possible do disable the dot and content animation by settings their `expandAnimationTiming` and `collapseAnimationTiming` to `0ms`. However this does not keep the dot in its initial position which may be the desired outcome here. 

I am keeping this closed and keep track of this additional feature (keeping the dot in its initial position) in #45
