### ISSUE TITLE
responsive timeline

### ISSUE THREAD

**Issue by Developbeard** [glutengo/angular-mgl-timeline#19]
Hello,
I am creating a page where a timeline is necessary, the timeline was created correctly but when I open the page the timeline is generated with the mobile class, how can I change the minimum resolution to create that variable?

**Comment by sargent88** [comment]
I'm having this same issue, I think it has something to do with the ngAfterViewInit in the timeline.component.ts file. It will switch from mobile to normal view on a window resize, but default behavior is mobile first. I tried to remove the class, but that didn't really work and wouldn't style it correctly either. Also, the this.elementRef.nativeElement.clientWidth keeps returning 0 for me, so I'm not even totally sure how it's recognizing the changes...

I'll keep digging into it and see what I can figure out as it's necessary for my project too.

**Comment by glutengo** [comment]
Hey, could you please provide an example on stackblitz? If you do so, I can look into it.

From what @sargent88 is saying, I'd expect the root element to not have any width because it may not have display:block. But again, Please provide a stackblitz example and I'll help.

**Comment by cribbstechnologies** [comment]
@glutengo If you open your own stackblitz demo it happens if the window is resized small enough.

**Comment by glutengo** [comment]
PR merged, Release 0.3.1 was created and published on NPM. Thanks!
