### ISSUE TITLE
BrowserAnimationsModule required?

### ISSUE THREAD

**Issue by guillaumegarcia13** [glutengo/angular-mgl-timeline#2]
It seems that importing BrowserAnimationsModule  is not optional. (tried removing it in the Stackblitz demo)
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

Thanks for your confirmation.

**Comment by glutengo** [comment]
It is indeed mandatory. Feel free to add the info in a pull request. Otherwise I‘ll update it myself in a couple of weeks (currently on vacation)
