### ISSUE TITLE
Add Angular Input for left/right direction

### ISSUE THREAD

**Issue by Etiake** [glutengo/angular-mgl-timeline#22]
Hi to all,
I see that if [alternate] is set to false, all entries are shown to the left of the timeline. The only way to show them on the right is to force the mobile width (am I right?). It will be useful - in my opinion - to add something like [symmetry] property to mgl-timeline to configure the default direction when alternate is false.
Let me know :)

**Comment by glutengo** [comment]
Hi, good suggestion! I included a new option called `side` in the new release (0.3.0). It can be set to either `left` (default) or `right`.
Note: It is not taken into account when `alternate` is set to `true`.

You can check it out in the demo: https://angular-mgl-timeline.stackblitz.io/
