### ISSUE TITLE
.mobile class is removed between 670px and 767px

### ISSUE THREAD

**Issue by newcreativegamer** [glutengo/angular-mgl-timeline#24]
Hi,

Weird one here, the .mobile class is present below 670px screen width and between 767px and 863px.
However, it is missing between 670px and 767px. How can I get around this?

Thanks,
Alan.

**Comment by cribbstechnologies** [comment]
I created this PR to allow the mobile class trigger width to be configurable. You could clone my branch and try adjusting the settings to see if you can find one that works for your case.
https://github.com/glutengo/angular-mgl-timeline/pull/23

**Comment by glutengo** [comment]
...cloning won't be needed anymore now as the PR was merged. Please update to v 0.3.1 and try the new `mobileWidthThreshold` option
