### ISSUE TITLE
Cannot toggle on iOS Chrome, iOS Safari, etc.

### ISSUE THREAD

**Issue by AndersTornkvist** [glutengo/angular-mgl-timeline#25]
It is not possible to toggle an entry by clicking on the header on some mobile devices, for example iOS Chrome (version 72.0.3626.101), iOS Safari (iOS 12.1.4).

**Comment by glutengo** [comment]
should be fixed in v 0.3.2 thanks to this PR: https://github.com/glutengo/angular-mgl-timeline/pull/26

Please give me some feedback if this works for you

**Comment by AndersTornkvist** [comment]
Thank you @glutengo for having a look at and including the PR in master. The functionality now works in v 0.3.2 on the mobile devices where I discovered the problem. I will therefore close this issue.
