### ISSUE TITLE
Request: Unanimated dot

### ISSUE THREAD

**Issue by UnGaucho** [glutengo/angular-mgl-timeline#28]
The idea is to keep the dot unmovable while still allowing the expanding feature. Couldn't find a way to override the animation or stop the event propagation so I had to modify the lib.

Awesome timeline btw!

**Comment by Etiake** [comment]
I understand what you mean. The dot is a way to track the position of the timeline-entry on the timeline. I think it's a matter of UX.

**Comment by UnGaucho** [comment]
Absolutely, though having an unmovable dot plus the header and expanding content is usually enough. 

The problem arises when you have too many timeline expanded entries interleaved. Usually what you look first in a timeline is the central piece then your focus moves to the sides.

The dot acts as a central piece that pins the entry to the timeline. If the dot moves you end up needing to  focus on each header which could be on both sides. This becomes a point of friction when it comes to UX. This problem becomes even more noticeable on smaller screens such as a mobile device.

I did solve my issue though by forking and disabling the dot animation but I figured it would be a nice feature to ask for when it comes to customizability.

Nevertheless it's an awesome timeline, thanks for sharing!

**Comment by glutengo** [comment]
It is now possible do disable the dot animation by settings the `expandAnimationTiming` and `collapseAnimationTiming` to `0ms`. However this does not keep the dot in its initial position which may be the desired outcome here. 

I am keeping this closed and keep track on the additional feature (keeping the dot in its initial position) on the linked issue.
