### ISSUE TITLE
problem accessing to css

### ISSUE THREAD

**Issue by mariuschiriac** [glutengo/angular-mgl-timeline#30]
i've read in the release 0.3.0 was fixed this problem, but i cannot figure it out.
im trying to access to `.mgl-timeline-line {
  background-color: aqua;}` and set it background color but it seems to be ignored in any way possible.

any help should be appreciated. 

thanks

**Comment by marcosrbertuol** [comment]
any lucky ? Same issue here

**Comment by mariuschiriac** [comment]
> any lucky ? Same issue here

unfortunately not, i wrote my own timeline component

**Comment by marcosrbertuol** [comment]
Yeah man, so did I. Thanks for replying
