### ISSUE TITLE
Collapse animation not working (Angular 7)

### ISSUE THREAD

**Issue by gmerwan** [glutengo/angular-mgl-timeline#34]
I'm having an issue with the collapse animation
when I click for collapsing it freezes.
Any one had that issue ?

**Comment by glutengo** [comment]
Can you please provide an example where this happens (maybe on stackblitz or somewhere similar). It would also be great if you could add some details about which browser etc.

**Comment by gmerwan** [comment]
I figured it out. It was just a miss alignment of components.
