### ISSUE TITLE
Dot not appearing on timeline in Angular 8.1.2

### ISSUE THREAD

**Issue by Cantum2** [glutengo/angular-mgl-timeline#36]
**Issue**
When adding the dot to the timeline it simply does not appear on to the timeline

**Expected Behavior**
The dot appearing to the timeline as seen in the docs

**Dependencies**
```
 "@angular/animations": "^8.1.2",
    "@angular/cdk": "^8.1.1",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/material": "^8.1.1",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "angular-mgl-timeline": "^0.3.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
```

**Code**
```
<mgl-timeline>
    <mgl-timeline-entry>
        <mgl-timeline-entry-header>Header</mgl-timeline-entry-header>
        <mgl-timeline-entry-content>Content</mgl-timeline-entry-content>
        <mgl-timeline-entry-dot></mgl-timeline-entry-dot>
    </mgl-timeline-entry>
</mgl-timeline>
```

That is the exact code I have implemented. The dot does not appear on the UI. Here is an image of what is being displayed. 
![image](https://user-images.githubusercontent.com/26589485/61990204-2b51a800-aff9-11e9-9bdb-2ec2f6fc7ff8.png)

**Comment by glutengo** [comment]
I haven't checked with Angular 8 yet. I'll have to test this and do an update.

**Comment by hakim-dc** [comment]
Are there any plans to fix this in the incoming release?

**Comment by RichardZandi** [comment]
I get the dot in Angular 8.1.2:

<mgl-timeline-entry-dot [size]="size"
                                           style="text-align: center; background-color: lightblue; color: darkblue">
</mgl-timeline-entry-dot>

**Comment by Mankunian** [comment]
> <mgl-timeline-entry-dot [size]="size"
> style="text-align: center; background-color: lightblue; color: darkblue">

thank you. it works!
