### ISSUE TITLE
duplicated entry for 'Add Entry'. Help Needed!

### ISSUE THREAD

**Issue by deborahtrez** [glutengo/angular-mgl-timeline#37]
Okay when you click the button 'Add Entry', it adds an exact duplicate of the first entry.. im trying to  create a timeline for different years whereby the headers contain the years  e.g, 2018, 2019, 2020....etc and the content section will have different content for each entry. but the Add Entry function pushes (adds to the array) an exact duplicate of the first entry due to "entries" defined in the ts file as as shown below.....
(please see the attached photos)

is there a  way of maybe defining different entries to hold different header and content material as opposed to the duplication. i want every object in the array "entries" to have different content.
![entries](https://user-images.githubusercontent.com/28389950/61994021-cd1ad880-b07d-11e9-9449-95fee692caa4.PNG)
![duplicated](https://user-images.githubusercontent.com/28389950/61994035-dd32b800-b07d-11e9-8417-a21decc5c435.PNG)

**Comment by glutengo** [comment]
Of course this is possible - you just need to insert different content into the entries array. Right now your ```addEntries``` function always adds the same content. This is not really related to the library.
