### ISSUE TITLE
Angular 9 Ivy

### ISSUE THREAD

**Issue by cpro90** [glutengo/angular-mgl-timeline#43]
Hey there,

how are chances you make mgl timeline Angular 9 compatible? :)

Best

**Comment by glutengo** [comment]
Angular 9 support is planned, no timeline yet. Closing this as a duplicate to #46

**Comment by cpro90** [comment]
#46 is the duplicate to #43, not the opposite ;)

**Comment by glutengo** [comment]
@cpro90 yea you're totally right there - I just favored the other ticket because it contains more information and some helpful instructions on what changes might be required
