### ISSUE TITLE
Angular 9 update

### ISSUE THREAD

**Issue by ivilchak** [glutengo/angular-mgl-timeline#46]
The lib does not work with new Angular versions due to critical changes:
core: The deprecated type Renderer has been removed. Use Renderer2 instead.

https://github.com/angular/angular/blob/master/CHANGELOG.md#code-refactoring

Any way to update?
Thanks.

**Comment by glutengo** [comment]
Angular 9 support is planned, but no timeline yet as I am busy with work and university.

I'm happy to accept PRs addressing this!

**Comment by larjohn** [comment]
I was to lazy/busy to make a PR
https://github.com/larjohn/angular-mgl-timeline/commits/master

**Comment by Wheater** [comment]
@larjohn how can I get this in an NPM package?

**Comment by larjohn** [comment]
That is why I didn't bother to make a PR; package would be available later. So I made my own:

    "angular-mgl-timeline.9": "^0.3.5",

**Comment by davidHaunschmied** [comment]
Hi @larjohn, thanks for your awesome work!
Any chance you are going to file a PR for that?

**Comment by larjohn** [comment]
I have also added npm stuff to my fork, I don't know how to keep the existing and make a new one and a PR.

**Comment by glutengo** [comment]
@larjohn thanks so much for your work! 

I have cherry-picked your [commit](https://github.com/larjohn/angular-mgl-timeline/commit/680bbf5ca5ed1d5a20cbcb933b333a99f8ab56bb) and released a new version (0.3.3)
