### ISSUE TITLE
Error:  TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by AnthonyNahas** [glutengo/angular-mgl-timeline#48]
I've just updated the library from `0.3.2` to `0.3.3`

and I've got the following errors:

<img width="1427" alt="Bildschirmfoto 2020-03-29 um 21 25 30" src="https://user-images.githubusercontent.com/20149774/77858459-022a8c80-7204-11ea-8f02-1f90db6b3e08.png">

the project can't be compiled anymore

**Comment by glutengo** [comment]
Hi @AnthonyNahas and thanks for your interest in the library.

A bit of googling led my to the assumption that this may be a typescript issue. Could you please try to use a newer version of typescript or set `skipLibCheck` to true in your tsconfig as suggested [here](https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context/58804230#58804230)?

Please let me know if either helps.

**Comment by MauricioGeinfo** [comment]
Hi @glutengo!
I had the same error, i added `"skipLibCheck": true` in ` tsconfig.json` and it worked.
