### ISSUE TITLE
Stackblitz demo gives an error

### ISSUE THREAD

**Issue by onurkanbakirci** [glutengo/angular-mgl-timeline#86]
Demo in stackblitz link gives following error;
<img width="550" alt="Screen Shot 2022-06-18 at 10 20 55" src="https://user-images.githubusercontent.com/50163185/174427527-28efb6ff-0cc4-4414-b678-fe2050be5ca9.png">

**Comment by glutengo** [comment]
the stackblitz demo should be OK again now.
