### ISSUE TITLE
Wrong install command on your NPM page 

### ISSUE THREAD

**Issue by nicknijenhuis** [glutengo/angular-mgl-timeline#9]
On your NPM page there is an install command in the `Getting Started` section:
https://www.npmjs.com/package/angular-mgl-timeline

**Actual result:**
Getting started
run npm install --save mgl-angular-timeline

**Expected result:**
Getting started
run npm install --save angular-mgl-timeline

Pretty sure this is just an old readme and should be replaced with the one on GitHub.

**Comment by guillaumegarcia13** [comment]
You're right.
I proposed a PR and it has been accepted (hence the updated README) but @glutengo is not yet back from vacation to update NPM page.

**Comment by nicknijenhuis** [comment]
I was looking for to update this myself in the repo. But if I understand correctly, updating the NPM page is a manual action? Wouldn't it by nice if it would just use the README from the github page directly?

**Comment by glutengo** [comment]
It does use the README from the repository. I will just have to do a release and then update the version on NPM via npm publish. I‘m flying back later today, the update will happen this weekend or early next week.

**Comment by glutengo** [comment]
Should be good now. I made a new release (0.1.8) and published it on NPM. Thank you guys for taking care of the README issue in the meantime!
